import { CSSProperties } from 'react';
import './NyanToaster.scss';

interface NyanToasterProps {
  /**
   * Whole-number pixel scale (keeps every art pixel a crisp square). Omit for
   * the responsive default: 3x on phones (261x120), 5x on desktop (435x200).
   */
  scale?: number;
  className?: string;
}

/**
 * The animated toastercat: a 6-frame sprite sheet (87x40 per frame) stepped
 * through at ~14fps, Nyan Cat's cadence. Frames are generated by
 * scripts/build-nyan-sprite.py from the static toastercat sprite.
 *
 * Purely decorative, and holds a single frame under reduced motion. Best kept
 * to spots that can afford to be playful (it's the 404 splash today).
 */
export default function NyanToaster(props: NyanToasterProps) {
  const style = props.scale
    ? ({ '--scale': Math.max(1, Math.round(props.scale)) } as CSSProperties)
    : undefined;

  return (
    <div
      className={`nyan-toaster ${props.scale ? 'nyan-toaster--fixed' : ''} ${props.className ?? ''}`}
      style={style}
      role="presentation"
      aria-hidden="true"
    />
  );
}
